tap "koekeishiya/formulae"
tap "FelixKratz/formulae"

brew "stow"
brew "jq"
brew "git"
brew "eza"
brew "zsh"
brew "tmux"
brew "sesh"
brew "nvim"
brew "wget"
brew "node"
brew "go"
brew "fzf"
brew "gum"
brew "zoxide"
brew "rbenv"
brew "yabai"
brew "skhd"
brew "black"
brew "hg"
brew "viu"
brew "chafa"
brew "sketchybar"
brew "isort"
brew "prettierd"
brew "urlview"
brew "imagemagick"
brew "pngpaste"
brew "ansifilter"
# brew "fpp" #for opening files in tmux fpp (USELESS)

# for tunneling
brew "ttyd"
brew "cloudflared"

cask "google-chrome"
cask "ghostty"
cask "zen"
cask "ghostty"
cask "hammerspoon"