return {
  "jojoyuji/megaman-vim",
  "jojoyuji/nyancat-vim",
  -- operations,
  "rhysd/clever-f.vim",
  "haya14busa/incsearch.vim",
  "dietsche/vim-lastplace",
  -- quickfix,
  "stefandtw/quickfix-reflector.vim",
  -- utilities
  'sk1418/HowMuch',
  "dstein64/vim-startuptime",
  "kylef/apiblueprint.vim",
  "mattn/emmet-vim",
  "Raimondi/delimitMate",
  "evanleck/vim-svelte",
  -- " tmux,
  "tmux-plugins/vim-tmux-focus-events",
  "wellle/tmux-complete.vim",
  "christoomey/vim-tmux-navigator",
  -- syntax
  "elzr/vim-json",
  "tpope/vim-repeat",
  "tpope/vim-unimpaired",
  "andymass/vim-matchup",
  "editorconfig/editorconfig-vim",
  "posva/vim-vue",
  "tpope/vim-dispatch",
}
